// <auto-generated />
using System;
using LibraryAccounting.Infrastructure.Repositories;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace LibraryAccounting.Infrastructure.Repositories.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20210908140127_7")]
    partial class _7
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("LibraryAccounting.Domain.Model.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Author")
                        .HasColumnType("text");

                    b.Property<string>("Genre")
                        .HasColumnType("text");

                    b.Property<string>("Publisher")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Кехо Джон",
                            Genre = "Психология",
                            Publisher = "Попурри",
                            Title = "Подсознание может все!"
                        },
                        new
                        {
                            Id = 2,
                            Author = "Некто",
                            Genre = "Наука",
                            Publisher = "Москва",
                            Title = "История"
                        },
                        new
                        {
                            Id = 3,
                            Author = "Некто",
                            Genre = "Наука",
                            Publisher = "Москва",
                            Title = "Биология"
                        },
                        new
                        {
                            Id = 4,
                            Author = "Некто",
                            Genre = "Наука",
                            Publisher = "Питер",
                            Title = "Химия"
                        },
                        new
                        {
                            Id = 5,
                            Author = "Стивен Кови",
                            Genre = "Книги по личностному росту от Стивена Кови",
                            Publisher = "Альпина Паблишер",
                            Title = "Семь навыков высокоэффективных людей."
                        },
                        new
                        {
                            Id = 6,
                            Author = "А. Ивич; Рис. Э. Беньяминсона, Б. Кыштымова",
                            Genre = "Детская литература",
                            Publisher = "Москва",
                            Title = "Семьдесят богатырей"
                        },
                        new
                        {
                            Id = 7,
                            Author = "Д.И. Менделеев",
                            Genre = "Наука",
                            Publisher = "АСТ",
                            Title = "Периодическая система химических элементов"
                        });
                });

            modelBuilder.Entity("LibraryAccounting.Domain.Model.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("BookId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("BookingDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("ClientId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsReturned")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsTransmitted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("ReturnDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("TransferDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("Bookings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BookId = 3,
                            BookingDate = new DateTime(2021, 9, 8, 17, 1, 27, 167, DateTimeKind.Local).AddTicks(3946),
                            ClientId = 1,
                            IsReturned = false,
                            IsTransmitted = false
                        });
                });

            modelBuilder.Entity("LibraryAccounting.Domain.Model.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "client"
                        },
                        new
                        {
                            Id = 2,
                            Name = "librarian"
                        },
                        new
                        {
                            Id = 3,
                            Name = "admin"
                        });
                });

            modelBuilder.Entity("LibraryAccounting.Domain.Model.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .HasColumnType("text");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "Ivan@gmail.com",
                            Name = "Иван",
                            Password = "1234567890",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 2,
                            Email = "Danil@gmail.com",
                            Name = "Данил",
                            Password = "1234567890",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 3,
                            Email = "Denis@gmail.com",
                            Name = "Денис",
                            Password = "dasf34rfew43",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 4,
                            Email = "Vanek@gmail.com",
                            Name = "Ваня",
                            Password = "23534534623423",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 5,
                            Email = "DemRh@gmail.com",
                            Name = "Дмитрий",
                            Password = "п54вув324ук",
                            RoleId = 1
                        });
                });

            modelBuilder.Entity("LibraryAccounting.Domain.Model.User", b =>
                {
                    b.HasOne("LibraryAccounting.Domain.Model.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("LibraryAccounting.Domain.Model.Role", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
